### ISSUE TITLE
Upgrade from 4.2.0 to 4.2.1 breaks when quiet_assets=true

### ISSUE THREAD

**Issue by whitelancer** [rocketjob/rails_semantic_logger#64] opened 2018-04-04 18:44 UTC
Hi there,

We recently did a bundle update of rsl and we do not get any logging into our standard log.  After troubleshooting it a bit, we rolled back to 4.2.0 and everything started working again.

I'm not sure what could be going on, exactly; we have the issue show up in all our environments, not just development (where we have more going on, with colorized logging, awesome print, extra appenders, etc).  Production is very simple -- we just use 2 options:
```
  config.colorize_logging = false
  config.rails_semantic_logger.quiet_assets = true
```

I believe this is the diff:

https://github.com/rocketjob/rails_semantic_logger/compare/b34180598d74675964f26b328291b39e574d4fe0...2a8a00b686a4f0a49c47ac3dd59146ad7cd7355b

I'm not sure what might be causing this.  Is anyone else experiencing this?

**Comment by PashaLVWD** [comment] 2018-04-05 15:27
@whitelancer if you take this chunk of code between lines
https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/engine.rb#L235
and
https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/engine.rb#L259
and move it here
https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/engine.rb#L223

Basically move require statements back into `config.before_initialize`, then it works with `config.rails_semantic_logger.quiet_assets = true`

**Comment by whitelancer** [comment] 2018-04-05 18:30
We've forked our own copy of this in order to fix this issue.  Hopefully it can be addressed in the official version of the gem!  Thanks.

**Comment by reidmorrison** [comment] 2018-04-10 20:10
The require statements were moved into the after initialize because Rails would sometimes not define some classes, preventing monkey-patches from being loaded.
Simply moving the monkey-patches into the before_initialize is not going to solve the load order problem that some people are seeing with Rails.

**Comment by reidmorrison** [comment] 2018-04-10 20:15
See: https://github.com/rocketjob/rails_semantic_logger/issues/50

**Comment by reidmorrison** [comment] 2018-04-10 20:25
Ah ok, I see that it has 2 after_initialize blocks. I just pushed a change to master, can you give that a try and let me know if it helps?

**Comment by reidmorrison** [comment] 2018-04-11 03:54
Changes have been made in master to replace several builtin Rails subscribers instead of patching them. It should help with the ongoing patching issues and loading order.
Give master a try locally and let us know if you run into any issues.

**Comment by whitelancer** [comment] 2018-04-11 17:36
After upgrading to test out this gem, I'm now seeing this error when trying to boot the application:
```
]$ be rails c
/home/whitelancer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/stack.rb:106:in `assert_index': No such middleware to insert before: Rails::Rack::Logger (RuntimeError)
        from /home/whitelancer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/stack.rb:73:in
`insert'
        from /home/whitelancer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.6/lib/rails/configuration.rb:69:in `block in merge_into'
        from /home/whitelancer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.6/lib/rails/configuration.rb:68:in `each'
        from /home/whitelancer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.6/lib/rails/configuration.rb:68:in `merge_into'
        from /home/whitelancer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.6/lib/rails/engine.rb:507:in `block in app'
        from /home/whitelancer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.6/lib/rails/engine.rb:504:in `synchronize'
        from /home/whitelancer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.6/lib/rails/engine.rb:504:in `app'
        from /home/whitelancer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.6/lib/rails/application/finisher.rb:45:in `block in <module:Finisher>'
```

I don't see anything jumping out at me about why this is happening, but I'll dig around to see if I can get a better understanding of the error.

**Comment by whitelancer** [comment] 2018-04-18 19:49
So far, I haven't been able to really pinpoint the cause here.  I'm going to rollback for a bit.  Let me know if you have any other ideas on how else to fix this.

**Comment by reidmorrison** [comment] 2018-04-26 13:27
I found the root cause was in Sprockets when it tries to quiet asset logging. Sprockets relies on the `Rails::Rack::Logger` being in the middleware stack, but it is now replaced with the `RailsSemanticLogger::Rack::Logger`. I pushed a workaround so that Sprockets will work now.
Can you give the latest master a try?

**Comment by whitelancer** [comment] 2018-04-26 14:12
Hey, that did it!  Nice!  So far I'm not seeing any other issues.  

I did have to force my Gemfile to point to the git repo to pull down 4.3.0, but that does seem to fix this issue so far.  I'd say you are likely in a good spot to push to rubygems.  I'll keep doing more testing but that seems like it's fixed it so far.  Thanks for continuing to dig!

**Comment by reidmorrison** [comment] 2018-05-03 04:03
I did find one other issue that is now fixed. We have master running in our production environment, so should be able to publish a new gem soon.

**Comment by reidmorrison** [comment] 2018-05-03 04:04
Thank you for the feedback, makes it easier to know when the branch is ready to publish in a gem.

**Closed by reidmorrison** 2018-05-03 04:04 UTC
